language: android

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

sudo: false

jdk:
  - oraclejdk8

env:
  global:
    # Run android tests on api level 22
    - EMULATOR_API=22
    - EMULATOR_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - doc-26
    # Android tests
    - android-$EMULATOR_API
    - sys-img-$EMULATOR_ABI-android-$EMULATOR_API
    # sys-img-x86-google_apis-26

before_script:
  - echo no | android create avd --force --name test --target android-$EMULATOR_API --abi $EMULATOR_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew build connectedCheck testDebugUnitTest

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true