# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: Deploy
on:
  release:
    types: [published]
jobs:
  BINTRAY_UPLOAD:
    name: Bintray Upload
    runs-on: ubuntu-latest
    env:
      TRAVIS: true
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Perform bintray upload
        run: ./gradlew bintrayUpload
